kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: grpc-poc
  labels:
    app: grpc-poc
spec:
  rules:
    - host: grpc-poc-alinflorin.cloud.okteto.net
      http:
        paths:
          - path: /
            backend:
              serviceName: grpc-poc-ui-preact
              servicePort: 80
